### ISSUE TITLE
No video stream running on Raspberry

### ISSUE THREAD

**Issue by Saku241** [KhaosT/homebridge-camera-ffmpeg#378]
I use MotionEye on my raspberry for my camera so I got the stream URL to `192.168.1.2:8081`

I connected homebridge on my iPhone and the camera works with snapshots but when I want to see the live stream I got this error :

```
[10/30/2019, 12:08:58 AM] [Camera-ffmpeg] Snapshot from Camera Surveillance at 480x270
[10/30/2019, 12:09:09 AM] [Camera-ffmpeg] Start streaming video from Camera Surveillance with 1280x720@299kBit
[10/30/2019, 12:09:09 AM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
[10/30/2019, 12:09:24 AM] [Camera-ffmpeg] Start streaming video from Camera Surveillance with 1280x720@299kBit
[10/30/2019, 12:09:24 AM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
```

Here's my config.json
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"ports": {
		"start": 52100,
		"end": 52150,
		"comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
	},
	"platforms": [{
		"platform": "Camera-ffmpeg",
		"cameras": [{
			"name": "Camera Surveillance",
			"videoConfig": {
				"source": "-re -i http://user:password@192.168.1.2:8081",
				"vcodec": "h264_omx",
				"maxStreams": 1,
				"maxWidth": 480,
				"maxHeight": 270,
				"maxFPS": 15
			}
		}]
	}]
}
```

**Comment by Saku241** [comment]
I fixed it by refering the correct ffmpeg by adding `"videoProcessor": "/usr/bin/ffmpeg",`

see my config.json now : 
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"ports": {
		"start": 52100,
		"end": 52150,
		"comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
	},
	"platforms": [{
		"platform": "Camera-ffmpeg",
		"videoProcessor": "/usr/bin/ffmpeg",
		"cameras": [{
			"name": "Camera Surveillance",
			"model": "MotionEye",
			"videoConfig": {
				"source": "-re -i http://user:password@192.168.1.2:8081",
				"vcodec": "h264_omx",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 15
			}
		}]
	}]
}
```

**Comment by iAmRenzo** [comment]
This is my config.json, but I still see no images on my cam, only a red !

	    {
		"platform": "Camera-ffmpeg",
		"videoProcessor": "/usr/bin/ffmpeg",
		"cameras": [{
			"name": "Spycam",
			"manufacturur": "Raspberry Pi",
			"model": "Motion Eye",
			"videoConfig": {
				"source": "-re -i mjpeg http://admin:*******@192.168.2.39:8081",
				"stillImageSource": "-f mjpeg -i http://http://admin:*******@192.168.2.39:8765/picture/1/current/",
				"vcodec": "h264_omx",
				"maxStreams": 2,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 30
			}

But I don't see ffmpeg in /usr/bin/

**Comment by Saku241** [comment]
> This is my config.json, but I still see no images on my cam, only a red !
> 
> ```
>     {
> 	"platform": "Camera-ffmpeg",
> 	"videoProcessor": "/usr/bin/ffmpeg",
> 	"cameras": [{
> 		"name": "Spycam",
> 		"manufacturur": "Raspberry Pi",
> 		"model": "Motion Eye",
> 		"videoConfig": {
> 			"source": "-re -i mjpeg http://admin:*******@192.168.2.39:8081",
> 			"stillImageSource": "-f mjpeg -i http://http://admin:*******@192.168.2.39:8765/picture/1/current/",
> 			"vcodec": "h264_omx",
> 			"maxStreams": 2,
> 			"maxWidth": 1280,
> 			"maxHeight": 720,
> 			"maxFPS": 30
> 		}
> ```
> 
> And/but I don't see ffmpeg in /usr/bin/
> 
> And did you something to the config of Motion Eye?

Remove the mjpeg in source
Run `whereis ffmpeg` to locate your ffmpeg 
And run `ffmpeg -codecs` to se if h264_omx is  supported

**Comment by iAmRenzo** [comment]
I think we've got the problem...

pi@raspberrypi:~ $ whereis ffmpeg
ffmpeg:
pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ ffmpeg -codecs
bash: ffmpeg: command not found
pi@raspberrypi:~ $ 
I need to figure out how I can install ffmpeg! :D

I did change some things in MotionEye... shouldn't I have? How can I reset them to default?
